### PR TITLE
Update to new guidelines

### PR DESCRIPTION
**Pull request by hguemar**
- rename package to python2-keystoneauth1
- add missing python3 subpackage
- version provides
- rename spec file to reflect package name
- drop python-argparse (already in standard lib of python 2.7 and 3.x)

I ran mockbuild (fedora/rawhide), both python2 & python3 packages install and run (basic sanity checks only). I also verified provides, they look good.
No obsoletes, since it has only been shipped in delorean trunk

### CODE REVIEW

**Comment by hguemar** [comment]
@alphacc @apevec ^

**Comment by apevec** [comment]
Does it work with openstackclient? (see rdo-list ...)

**Comment by apevec** [comment]
@hguemar ^

**Comment by hguemar** [comment]
openstackclient does not complain anymore about keystoneauth1 module missing but another issue raised ``The plugin osc_password could not be found`

I haven't used %python_provide to minimize changes, it would generate exactly the same thing except `Obsoletes: python-keystoneauth1 = xxxx` which is not needed for a newly added package.

**Pull request merged**
